image: maven:3.8-openjdk-18

stages:
  - tests
  - allure

UI tests:
  stage: tests
  allow_failure: true
  script:
    - mvn clean test
  artifacts:
    when: always
    paths:
      - /target/allure-results/environment.properties

Allure report:
  stage: allure
  script:
    - mvn io.qameta.allure:allure-maven:report
    - echo "Allure report live here - ссылка на репорт http://192.168.1.232:53812/"
  artifacts:
    when: always
    paths:
      - /builds/spashkovskyi/Automation_Framework_CiproBet/target/site/allure-maven-plugin
