image: maven:3.8-openjdk-18

stages:
  - tests
  - allure

UI tests:
  stage: tests
  allow_failure: true
  script:
    - mvn clean test
  artifacts:
    when: always
    paths:
      - /target/allure-results/environment.properties

Allure report:
  stage: allure
  script:
    - mvn allure:report
    - echo "Allure report live here - ссылка на репорт "
  artifacts:
    when: always
    paths:
      - build/report/allure-report/allureReport/*
